apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: istiyaqmi9/ems_configserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083

---

apiVersion: v1
kind: Service
metadata:
  name: configserver-service
spec:
  selector:
    app: configserver
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: NodePort
