apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-filter
  labels:
    app: employee-filter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-filter
  template:
    metadata:
      labels:
        app: employee-filter
    spec:
      containers:
        - name: employee-filter
          image: istiyaqmi9/ems_employeeperfilter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8091

---

apiVersion: v1
kind: Service
metadata:
  name: employee-filter-service
spec:
  selector:
    app: employee-filter
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: NodePort
