apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-setting-pv
spec:
  capacity:
    storage: 10Ki
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/projects/hiringbell/Documents/appsettings.json
    type: DirectoryOrCreate