apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exceptionfiles-pvc
spec:
  volumeName: exceptionfiles-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi