apiVersion: v1
kind: PersistentVolume
metadata:
  name: exceptionfiles-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /root/projects/hiringbell/ExceptionFiles
    type: DirectoryOrCreate